add terraform plan

diff --git a/.github/workflows/deploy-infra.yml b/.github/workflows/deploy-infra.yml
--- a/.github/workflows/deploy-infra.yml
+++ b/.github/workflows/deploy-infra.yml
@@ -33,5 +33,22 @@ jobs:
 
       - name: Terraform Validate
         id: validate
-        run: terraform validate -no-color        
+        run: terraform validate -no-color  
+
+      - name: Terraform Plan
+        id: plan
+        run: |
+          export exitcode=0
+          terraform plan -no-color -var-file="./main.tfvars.json" -out main.tfplan || export exitcode=$?
+
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 1 ]; then
+            echo "Error: Terraform plan failed"
+            exit 1
+          else
+            echo "Terraform plan was successful"
+            exit 0
+          fi          
+            
 
